name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Execute swont_ide.ioc
      run: ./swont_ide.ioc
    
    - name: Build makefile
      run: make all ./Debug/makefile

      
    - name: build main.c 
      run: make ./Core/Src/main.c
      
    - name: build all (debug)
      run: make ./Debug/swont_ide.elf
      
      
    

